export const STATE_LOADING = 'STATE_LOADING'
export const STATE_LOADING_PAGE = 'STATE_LOADING_PAGE'
export const STATE_ERROR = 'STATE_ERROR'
export const STATE_NO_RESULTS = 'STATE_NO_RESULTS'
export const STATE_NO_FILTERED_RESULTS = 'STATE_NO_FILTERED_RESULTS'
export const STATE_NO_ASSIGNED_VOICEMAILS = 'STATE_NO_ASSIGNED_VOICEMAILS'
export const STATE_SUCCESS = 'STATE_SUCCESS'
export const STATE_READY = 'STATE_READY'
export const STATE_UNAUTHORIZED = 'STATE_UNAUTHORIZED'
export const STATE_DELETED = 'STATE_DELETED'
export const STATE_UNINITIALIZED = 'STATE_UNINITIALIZED'

export const STATE_VOICEMAIL_RESOLVED = 'STATE_VOICEMAIL_RESOLVED'
export const STATE_VOICEMAIL_OPEN = 'STATE_VOICEMAIL_OPEN'

export const EMPTY_STATES = [
  STATE_ERROR,
  STATE_NO_RESULTS,
  STATE_NO_FILTERED_RESULTS,
  STATE_NO_ASSIGNED_VOICEMAILS
]
export const ALL_TABLE_STATES = [...EMPTY_STATES, STATE_LOADING, STATE_LOADING_PAGE, STATE_READY]
export const ALL_RECORDINGS_STATES = [
  STATE_LOADING,
  STATE_ERROR,
  STATE_READY,
  STATE_UNAUTHORIZED,
  STATE_DELETED,
  STATE_UNINITIALIZED
]
export const ALL_TRANSCRIPTION_STATES = [STATE_LOADING, STATE_ERROR, STATE_NO_RESULTS, STATE_READY]
