export const VOICEMAIL_OPEN_FILTER_VALUE = 'open';
export const VOICEMAIL_RESOLVED_FILTER_VALUE = 'resolved';
export const VOICEMAIL_STATUS_ALL_FILTER_VALUE = 'ALL'

export const VOICEMAIL_STATUS_FILTER_LIST = [VOICEMAIL_OPEN_FILTER_VALUE, VOICEMAIL_RESOLVED_FILTER_VALUE]
