export const apiScopes = [
    'account:read',
    "contacts:read",
    'contact-details:read',
    'contact-details:write',
    'contacts-activities:read',
    'graph-users:read',
    'numbers:read',
    'openid',
    'policies:evaluate',
    'recordings:read',
    'account-favorites:read',
    'account-custom-fields:read',
    'apps:graphql',
    'interaction-contacts:read',
    'ring-groups:read',
    'voicemails:read',
    'voicemails:write'
]
