export const INBOUND = 'INBOUND'
export const MISSED_INBOUND = 'MISSED_INBOUND'
export const OUTBOUND = 'OUTBOUND'
export const UNANSWERED_OUTBOUND = 'UNANSWERED_OUTBOUND'
export const ABANDONED = 'ABANDONED'
export const TRANSFER = 'TRANSFER'
export const INBOUND_SMS = 'INBOUND_SMS'
export const OUTBOUND_SMS = 'OUTBOUND_SMS'

export const activityTypes = [INBOUND,MISSED_INBOUND,OUTBOUND, UNANSWERED_OUTBOUND, ABANDONED, TRANSFER, INBOUND_SMS, OUTBOUND_SMS]
