export const STATUS_LOADING = 'STATUS_LOADING'
export const STATUS_ERROR = 'STATUS_ERROR'
export const STATUS_NO_RESULTS = 'STATUS_NO_RESULTS'
export const STATUS_READY = 'STATUS_READY'
export const STATUS_FILTER_NO_RESULTS = 'STATUS_FILTER_NO_RESULTS'

export const ALL_EMPTY_STATUS = [
  STATUS_ERROR,
  STATUS_NO_RESULTS,
  STATUS_FILTER_NO_RESULTS
]
export const ALL_STATUS = [...ALL_EMPTY_STATUS, STATUS_LOADING, STATUS_READY]
